### ISSUE TITLE
This is what i get when running the main.sh script

### ISSUE THREAD

**Issue by DinoTheDevOfficial** [afnan007a/Replit-vm#3]
main.sh: 47: Syntax error: "}" unexpected (expecting "fi")

**Comment by afnan007a** [comment]
lemme check

**Comment by afnan007a** [comment]
http://share-x.redknight.xyz/uploads/ps5aub0.png it works fine for me tho. are u using it in replit or?

**Comment by afnan007a** [comment]
http://share-x.redknight.xyz/uploads/zbjdbb4.png after installing it still works!

**Comment by DinoTheDevOfficial** [comment]
Hm thats weird o it might be because if copying and pasting
