### ISSUE TITLE
Gets stuck on this everytime

### ISSUE THREAD

**Issue by RehanPlayz** [afnan007a/Replit-vm#4]
It successfully installed everything and started but after some time I get this (Attached Image)
![Error](https://user-images.githubusercontent.com/63925635/143826340-cccbec6d-09ea-4e6f-b751-d88c1e5017b8.png)
 @afnan007a

**Comment by RehanPlayz** [comment]
nvm seemed to be fixed

**Comment by RehanPlayz** [comment]
It seems like this is happening when I run the command "xmrig -o rx.unmineable.com:3333 -a rx -k -u SHIB:0xDEcDA3d4bfA4E614A383c17F4E01DD8E0DA9abFE.my_cpu_miner -p x"

**Comment by RehanPlayz** [comment]
> nvm seemed to be fixed

It's stuck again now

**Comment by RehanPlayz** [comment]
"cd" command doesn't seem to work properly

**Comment by RehanPlayz** [comment]
> "cd" command doesn't seem to work properly

A workaround for this is using "shell" instead of "console"

**Comment by afnan007a** [comment]
> It seems like this is happening when I run the command "xmrig -o rx.unmineable.com:3333 -a rx -k -u SHIB:0xDEcDA3d4bfA4E614A383c17F4E01DD8E0DA9abFE.my_cpu_miner -p x"

u cant mine in replit btw
cuz replit blocked the word `xmrig` so to bypass it just use the replit-abooz in my github portfolio. and the cd command works fine for me

**Comment by afnan007a** [comment]
u can test it by just typing `xmrig` in replit and btw i havnt added any miner in replit-vm script. so u need to install it

**Comment by afnan007a** [comment]
its cuz replit free plan only give little space and if u install package it will take roughly 2gb space

**Comment by RehanPlayz** [comment]
> its cuz replit free plan only give little space and if u install package it will take roughly 2gb space

oh ok also I can't seem to install nodejs and npm using NodeSource

**Comment by RehanPlayz** [comment]
when i run 'npm" i get a error

**Comment by RehanPlayz** [comment]
Installing nodejs and npm normally (without nodesource) works fine but the nodejs version is outdated

**Comment by afnan007a** [comment]
> when i run 'npm" i get a error

install npm first
`apt install npm`

**Comment by afnan007a** [comment]
http://share-x.redknight.xyz/uploads/gvlyhay.png these are the preinstalled packages in replitvm

**Comment by RehanPlayz** [comment]
oh ok

**Comment by RehanPlayz** [comment]
> > when i run 'npm" i get a error
> 
> install npm first `apt install npm`

ok

**Comment by afnan007a** [comment]
can i close this?

**Comment by RehanPlayz** [comment]
> > It seems like this is happening when I run the command "xmrig -o rx.unmineable.com:3333 -a rx -k -u SHIB:0xDEcDA3d4bfA4E614A383c17F4E01DD8E0DA9abFE.my_cpu_miner -p x"
> 
> u cant mine in replit btw cuz replit blocked the word `xmrig` so to bypass it just use the replit-abooz in my github portfolio. and the cd command works fine for me

You mean railway-abooz?
