### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by blgoreuxe** [afnan007a/Replit-vm#7]
it keeps popping up with proot info: vpid 1: terminated with signal 11

**Comment by afnan007a** [comment]
installed properly?

**Comment by blgoreuxe** [comment]
> installed properly?

i fixed it, but is it possible for me to install qemu on this and then connect with a vnc and get windows as a vm?

**Comment by afnan007a** [comment]
if im correct replit only gives one port (maybe im wrong) and only like 2-5gb disk so i dont recommend doing it.

**Comment by blgoreuxe** [comment]
> if im correct replit only gives one port (maybe im wrong) and only like 2-5gb disk so i dont recommend doing it.

ok i already noticed that because i tried to install KDE after i said that

**Comment by afnan007a** [comment]
alright!
